### ISSUE TITLE
Project has issues importing into Android Studio on Unix

### ISSUE THREAD

**Issue by danoz73** [kanytu/example-parallaxrecycler#1]
Upon attempting to open the project in Android Studio on a Mac, I get the following error:

``` java
Error:Illegal character in opaque part at index 2: E:\Development\android\MyApplication3\parallaxrecyclerview
```

**Comment by kanytu** [comment]
I ain't gonna guess what issues they are. Closed until more information is provided

**Comment by danoz73** [comment]
I have submitted a fix here: https://github.com/kanytu/example-parallaxrecycler/pull/2
